---
defaults:
  version: '2018.3'
net_ip: 10.0.0
box: bento/ubuntu-16.04 #ubuntu/trusty64
shell_scripts:
  - all_script.sh
machines:
  - name: ubuntu-minion-01
    ip: '.100'
  - name: ubuntu-minion-02
    ip: '.101'
  - name: master
    box: ubuntu-server
    # boxurl: http://tmxyum.tmx.com/yum/images/target/vb/mac/rhel-7.5.virtualbox.box
    ip: '.10'
    mem: 2048
    cpus: 2
    packages:
      - salt-ssh
      - nmap
    shell_scripts:
      - master_scripts/vagrant_master_init.sh
    forwarded_ports:
      - guest: 5240
        host: 5240
    # synced_folders:
    #   - src: ./master.d
    #     dest: /etc/salt/master.d
    #     create: true
    #     owner: root
    #     group: root
    #   - src: ./salt
    #     dest: /srv/salt
    #     create: true
    #   - src: ./pillar
    #     dest: /srv/pillar
